# **Matric Calculator**

In [ ]:
# Step 1:  Function to get matrix input
import numpy as np
def get_matrix():
    try:
        # Ask user for matrix dimensions
        rows = int(input("Enter the number of rows: "))
        cols = int(input("Enter the number of columns: "))

        # Ask user to input all elements in one line
        print("Enter all matrix elements separated by spaces:")
        numbers = list(map(float, input().split()))

        # Validate number of elements
        if len(numbers) != rows * cols:
            raise ValueError("Number of elements doesn't match matrix size.")

        # Convert list into 2D matrix
        elements = [numbers[i * cols:(i + 1) * cols] for i in range(rows)]
        return np.array(elements)

    except ValueError as e:
        print("Error:", e)
        return None


In [ ]:
# Step 2: Function to perform matrix operations

def matrix_operations(A, B):
    print("\nMatrix A:\n", A)
    print("\nMatrix B:\n", B)

    # Addition
    try:
        print("\nAddition:\n", A + B)
    except ValueError:
        print("\nAddition: Matrices must have the same dimensions.")

    # Subtraction
    try:
        print("\nSubtraction:\n", A - B)
    except ValueError:
        print("\nSubtraction: Matrices must have the same dimensions.")

    # Element-wise Multiplication
    try:
        print("\nElement-wise Multiplication:\n", A * B)
    except ValueError:
        print("\nElement-wise Multiplication: Matrices must have the same dimensions.")

    # Dot Product
    try:
        print("\nDot Product:\n", np.dot(A, B))
    except ValueError:
        print("\nDot Product: Columns of A must equal rows of B.")

    # Transpose
    print("\nTranspose of A:\n", A.T)
    print("\nTranspose of B:\n", B.T)

    # Determinant of A
    try:
        print("\nDeterminant of A:", np.linalg.det(A))
    except np.linalg.LinAlgError:
        print("\nDeterminant of A: Not applicable (Matrix must be square).")

    # Inverse of A
    try:
        print("\nInverse of A:\n", np.linalg.inv(A))
    except np.linalg.LinAlgError:
        print("\nInverse of A: Not invertible.")

In [ ]:
# Step 3: Main program to run calculator
def main():
    print("==========================")
    print("MATRIX CALCULATOR")
    print("==========================")

    print("\nInput Matrix A:")
    A = get_matrix()
    if A is None:
        return

    print("\nInput Matrix B:")
    B = get_matrix()
    if B is None:
        return

    matrix_operations(A, B)

In [ ]:
# Step 5: Run the program
if __name__ == "__main__":
    main()

MATRIX CALCULATOR

Input Matrix A:
Enter the number of rows: 2
Enter the number of columns: 2
Enter all matrix elements separated by spaces:
3 4 6 2

Input Matrix B:
Enter the number of rows: 2
Enter the number of columns: 2
Enter all matrix elements separated by spaces:
3 5 7 2

Matrix A:
 [[3. 4.]
 [6. 2.]]

Matrix B:
 [[3. 5.]
 [7. 2.]]

Addition:
 [[ 6.  9.]
 [13.  4.]]

Subtraction:
 [[ 0. -1.]
 [-1.  0.]]

Element-wise Multiplication:
 [[ 9. 20.]
 [42.  4.]]

Dot Product:
 [[37. 23.]
 [32. 34.]]

Transpose of A:
 [[3. 6.]
 [4. 2.]]

Transpose of B:
 [[3. 7.]
 [5. 2.]]

Determinant of A: -17.999999999999996

Inverse of A:
 [[-0.11111111  0.22222222]
 [ 0.33333333 -0.16666667]]
