# **Introduction** **To** **Numpy**

**Numpy** **Creating** **Array**

In [ ]:
# Import the numpy library
import numpy as np

In [ ]:
# using list to create arrary
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [ ]:
# using tuple to create arrary
arr2 = np.array((1,2,3))
print(arr2)

[1 2 3]


In [ ]:
# check the version of numpy
import numpy as np
print(np.__version__)

2.0.2


In [ ]:
# create 0-D array
arr = np.array(42)
print(arr)

42


In [ ]:
# create 1-D arrary
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
# create 2-D arrary
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# create 3-D arrary
arr31 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr31)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
arr3 = np.array([[[1,2,3], [4,5,6],[2,3,4],[8,7,4]]])
print(arr3)

[[[1 2 3]
  [4 5 6]
  [2 3 4]
  [8 7 4]]]


In [ ]:
# Check how many dimensions that array have;
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
# higher dimensional arrays
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('n0. of dimesion', arr.ndim)

[[[[[1 2 3 4]]]]]
n0. of dimesion 5


In [ ]:
# initialize python numpy arrary with some functions(zeros, ones, constant, arange, linspace)
import numpy as np

zeros1 = np.zeros((2,3))
ones1 = np.ones((3,3))
constant1 = np.full((3,3), 42)
range1 = np.arange(0,10,2)  # start, stop, step
linspace1 = np.linspace(0,1,5)   #start, stop, num

print(zeros1)
print(ones1)
print(constant1)
print(range1)
print(linspace1)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[42 42 42]
 [42 42 42]
 [42 42 42]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# create numpy arrays with random numers generations

random1 = np.random.rand(2,3)                 # Random float values between 0 and 1. every number can have equal chance.
random2 = np.random.randn(3,3)                # Random float values from a standard normal distribution. Values can be negative or positive
random3 = np.random.randint(0,10, size=(3,3)) # Random integers within a given range. You specify: low, high, and size

print('-', random1)
print('-',random2)
print('-',random3)

- [[0.1902948  0.59678574 0.92300705]
 [0.84416478 0.53723275 0.85582815]]
- [[ 2.99384949  1.6425394   0.92667951]
 [-0.56460478  0.68840534  0.6379558 ]
 [ 0.39547506 -1.82252324 -0.88060255]]
- [[4 8 0]
 [8 6 5]
 [5 3 3]]


**Numpy** **Array** **Indexing**

In [ ]:
#  access first element from the list
arr1 = np.array([1,2,3,4,5])
print(arr1[0])

1


In [ ]:
# access second element from the list
print(arr1[1])

2


In [ ]:
# access 3rd and fifth value from the list and add them
print(arr1[2] + arr1[4])

8


In [ ]:
# access element value from first row, second column
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on first row:', arr[0, 1])

2nd element on first row: 2


In [ ]:
# access element value from second row and fifth column
print('5th element on 2nd row', arr[1, 4])

5th element on 2nd row 10


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2]) #Access the third element of the second array of the first array:
print(arr[1, 1, 2]) #Access the third element of the second array of the second array:

6
12


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [ ]:
''' print(cube[1, 2, 0]) — What does it mean?
It means:

1 → Go to block 1 (second big 2D array)
2 → From that block, go to row 2 (third row)
0 → From that row, go to column 0 (first element)'''

# Block - 0
cube = np.array([[[1, 2, 3],    # row 0
                  [4, 5, 6],    # row 1
                  [7, 8, 9]],   # row 2
# Block - 1
                 [[10, 11, 12],   # row 0
                  [13, 14, 15],   # row 1
                  [16, 17, 18]]]) # row 2

print(cube[1, 2, 0])

16


In [ ]:
# Boolean Indexing - based on condition

arr = np.array([10, 15, 20, 25, 30])

print(arr[arr > 20])                 # Select only the elements greater than 20
print(arr[(arr > 10) & (arr < 30)])  # Using AND (&) to filter values between 10 and 30
print(arr[(arr < 15) | (arr > 25)])  # Using OR (|) to filter values either less than 15 or greater than 25
print(arr[~(arr == 20)])             # Using NOT (~) to select values NOT equal to 20

[25 30]
[15 20 25]
[10 30]
[10 15 25 30]


In [ ]:
# Fancy Indexing – Selecting Values by Index List

arr = np.array([10, 20, 30, 40, 50])
print(arr[[0, 2, 4]])  # Select values at index 0, 2, and 4

[10 30 50]


In [ ]:
# Integer Array Indexing – Using Integer Arrays to Select Values

arr = np.array([1, 2, 3, 4, 5])
print(arr[[0, 2, 4]])  # Select values using integer array of indices

[1 3 5]


In [ ]:
# Ellipsis (...) in Indexing – Shortcut for Multidimensional Arrays

# Create a 3D array
cube = np.random.rand(4, 4, 4)

print(cube[..., 0])  # Select all from first two dimensions, and 0th slice from last dimension

[[0.80268931 0.46206896 0.44517591 0.90551886]
 [0.40994051 0.61639845 0.64409938 0.46385209]
 [0.41249139 0.92497109 0.43230136 0.38226263]
 [0.48290553 0.99374506 0.30949105 0.41640859]]


In [ ]:
# np.newaxis – Add Extra Dimension

arr = np.array([1, 2, 3])
print(arr[:, np.newaxis]) # Add a new axis to convert 1D to 2D (column vector)

[[1]
 [2]
 [3]]


In [ ]:
# Modifying Array Elements – Update or Replace Values

arr = np.array([1, 2, 3, 4])
arr[1:3] = 99

print(arr)  # Replace values at index 1 and 2 with 99

[ 1 99 99  4]


**Numpy** **Array** **Slicing**

In [ ]:
# slice the element from 1 to 5 index in given range
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [ ]:
# slice the element from index to 4 to the end of array
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [ ]:
# slice the element from beginning to the index 4.
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


In [ ]:
# slice the index 3 from the end to the index 1 from the end.
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


In [ ]:
# return every other elemeent from index 1 to 5
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [ ]:
# return every other element from entire array
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


In [ ]:
# From the second element, slice elements from index 1 to index 4 (not included):
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [ ]:
# From both elements, return index 2:

import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


In [ ]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])


[[2 3 4]
 [7 8 9]]


**Numpy** **Arrays** **Datatypes**

In [ ]:
# Get the data type of an array object:

import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


In [ ]:
# Get the data type of an array containing strings:

import numpy as np
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [ ]:
# Create an array with data type string

import numpy as np
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
# Create an array with data type 4 bytes integer:

import numpy as np
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
# A non integer string like 'a' can not be converted to integer (will raise an error):

import numpy as np
arr = np.array(['a', '2', '3'], dtype='i')

In [ ]:
# Change data type from float to integer by using 'i' as parameter value:

import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
# Change data type from float to integer by using int as parameter value:

import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [ ]:
# Change data type from integer to boolean:

import numpy as np
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


**Numpy** **Copy** v/s **View**

In [ ]:
# Make a copy, change the original array, and display both arrays:

import numpy as np

ori = np.array([1, 2, 3, 4, 5])
cop = ori.copy()
ori[0] = 42

print(ori)
print(cop)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
# Make a view, change the original array, and display both arrays:

import numpy as np

ori = np.array([1, 2, 3, 4, 5])
vw = ori.view()
ori[0] = 42

print(ori)
print(vw)


[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
# Make a view, change the view, and display both arrays:

import numpy as np

ori = np.array([1, 2, 3, 4, 5])
vw = ori.view()
vw[0] = 31

print(ori)
print(vw)

[31  2  3  4  5]
[31  2  3  4  5]


**Numpy** **Array** **Shape**

In [ ]:
import numpy as np

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr.shape)

(2, 5)


In [ ]:
arr = np.array([1,2,3,4,5], ndmin = 5)
print(arr)
print(arr.shape)

[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)


**Numpy** **Array** **Reshape**

In [ ]:
# Reshaping : 1-D to 2D

# creating a numpy array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

# printing array
print("Array : " + str(array))

# length of array
n = array.size

# N-D array N dimension
N = 4

# calculating M
M = n//N

# reshaping numpy array
# converting it to 2-D from 1-D array
reshaped1 = array.reshape((N, M))

# printing reshaped array
print("First Reshaped Array : ")
print(reshaped1)

# creating another reshaped array
reshaped2 = np.reshape(array, (2, 8))

# printing reshaped array
print("Second Reshaped Array : ")
print(reshaped2)

Array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
First Reshaped Array : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Second Reshaped Array : 
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [ ]:
# Reshaping : 1-D to 3-D

# creating a numpy array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

# printing array
print("Array : " + str(array))


# reshaping numpy array
# converting it to 3-D from 1-D array
reshaped = array.reshape((2, 2, 4))

# printing reshaped array
print("Reshaped 3-D Array : ")
print(reshaped)

Array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Reshaped 3-D Array : 
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [ ]:
# Reshaping N-D to 1-D array

# creating a numpy array
array = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# printing array
print(" 2-D Array : ")
print(array)

# reshaping numpy array
# converting it to 1-D from 2-D array
reshaped = array.reshape((9))

# or we can use unknown dimension
# reshaped = array.reshape((-1))

# printing reshaped array
print("Reshaped 1-D Array : ")
print(reshaped)

 2-D Array : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped 1-D Array : 
[1 2 3 4 5 6 7 8 9]


In [ ]:
# Reshaping using unknown dimension

# creating a numpy array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

# printing array
print("Array : " + str(array))


# reshaping numpy array
# converting it to 3-D from 1-D array
reshaped1 = array.reshape((2, 2, -1))

# printing reshaped array
print("First Reshaped Array : ")
print(reshaped1)


# converting it to 2-D array
reshaped2 = array.reshape((4, -1))

# printing reshaped array
print("Second Reshaped Array : ")
print(reshaped2)

Array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
First Reshaped Array : 
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
Second Reshaped Array : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
# Errors Occur during reshaping

# creating a numpy array
array = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# printing array
print(" 2-D Array : ")
print(array)


# reshaping numpy array
# converting it to 1-D from 2-D array
# reshaping it into 1, 5
reshaped = array.reshape((3, 2))

# or we can use

# printing reshaped array
print("Reshaped 1-D Array : ")
print(reshaped)

In [ ]:
# Reshape From 1-D to 2-D: 4rows and 3 cols

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Reshape From 1-D to 3-D: 2 block, 3 rows, 2 cols

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
# Check if the returned array is a copy or a view:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [ ]:
# Convert 1D array with 8 elements to 3D array with 2x2 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Flattening the arrays :Convert the array into a 1D array:

arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


**Numpy** **Array** **Resizing**

In [ ]:
# we have changed the shape of an array from 1x6 to 2x3.
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array permanently
arr.resize(2, 3)
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# If reshaped size is larger, NumPy fills extra values with 0 (auto-padding)

gfg = np.array([1, 2, 3, 4, 5, 6])

# Required values 12, existing values 6
gfg.resize(3, 4)
print(gfg)

[[1 2 3 4]
 [5 6 0 0]
 [0 0 0 0]]


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)

for elements in arr:
  print(elements)

[1 2 3 4 5 6 7 8]
1
2
3
4
5
6
7
8


In [ ]:
arr_2D = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
for elements in arr_2D:
  print(elements)

[1 2 3]
[4 5 6]
[7 8 9]


In [ ]:
arr_3d =  np.array([[[1,2,3],
                    [4,5,6]],
                    [[7,8,9],
                     [10,11,12]]])
for elements in arr_3d:
  print(elements)


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
for i in range(arr_2d.shape[0]):
  for j in range(arr_2d.shape[1]):
    print(arr_2d[i,j])

1
2
3
4
5
6
7
8
9


In [ ]:
arr = np.array([[4,5,3],
                [2,0,6],
                [7,1,9]])
rows, cols = arr.shape
for i in range(rows):
  for j in range(cols):
    print(f'Elements at ({i}, {j}) : {arr[i,j]}')

Elements at (0, 0) : 4
Elements at (0, 1) : 5
Elements at (0, 2) : 3
Elements at (1, 0) : 2
Elements at (1, 1) : 0
Elements at (1, 2) : 6
Elements at (2, 0) : 7
Elements at (2, 1) : 1
Elements at (2, 2) : 9


In [ ]:
arr = np.array([[1,2], [3,4]])

for x in np.nditer(arr):
  print(x)

1
2
3
4


**Numpy** **Arrays** **Join**

In [ ]:
arr1 = np.array([[1,2,3,4],
                 [5,6,7,8]])
arr2 = np.array([[9,10,11,12],
                 [13,14,15,16]])

result = np.concatenate((arr1, arr2), axis = 0)
print(result)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
arr1 = np.array([[1,2,3,4],
                 [5,6,7,8]])
arr2 = np.array([[9,10,11,12],
                 [13,14,15,16]])
result = np.concatenate((arr1, arr2), axis = 1)
print(result)

[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


In [ ]:
arr1 = np.array([1,2,3],)
arr2 = np.array([[9,10,11],
                 [13,14,15]])

expanded_arr1 = np.expand_dims(arr1, axis = 0)
result = np.concatenate((expanded_arr1, arr2), axis = 0)
print(result)

[[ 1  2  3]
 [ 9 10 11]
 [13 14 15]]


In [ ]:
arr1 = np.array([[1, 2],
                 [3, 4]])

# Create a 3D array
arr2 = np.array([[[5, 6],
                  [7, 8]],

                 [[9, 10],
                  [11, 12]]])
expanded_arr1 = np.expand_dims(arr1, axis = 2)
result = np.concatenate((expanded_arr1, arr2), axis = 2)
print(result)

[[[ 1  5  6]
  [ 2  7  8]]

 [[ 3  9 10]
  [ 4 11 12]]]


In [ ]:
arr1 = np.array([[[1, 2],
                  [3, 4]],

                 [[5, 6],
                  [7, 8]]])

arr2 = np.array([[[9, 10],
                  [11, 12]],

                 [[13, 14],
                  [15, 16]]])

# Concatenate along the third dimension (axis=2)
result = np.concatenate((arr1, arr2), axis=2)
print(result)

[[[ 1  2  9 10]
  [ 3  4 11 12]]

 [[ 5  6 13 14]
  [ 7  8 15 16]]]


In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
result = np.concatenate((arr1, arr2))
print(result)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
result = np.stack((arr1, arr2))
print(result)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
arr1 = np.array([[1,2,3,4],
                [6,7,8,9]])
arr2 = np.array([[11,12,13,14],
                 [15,16,17,18]])

result = np.stack((arr1, arr2), axis = 0)
print(result)

[[[ 1  2  3  4]
  [ 6  7  8  9]]

 [[11 12 13 14]
  [15 16 17 18]]]


In [ ]:
arr1 = np.array([[1,2,3,4],
                [6,7,8,9]])
arr2 = np.array([[11,12,13,14],
                 [15,16,17,18]])

result = np.stack((arr1, arr2), axis = 1)
print(result)

[[[ 1  2  3  4]
  [11 12 13 14]]

 [[ 6  7  8  9]
  [15 16 17 18]]]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
arr1 = np.array([[1,2,3,4],
                [6,7,8,9]])
arr2 = np.array([[11,12,13,14],
                 [15,16,17,18]])

result = np.stack((arr1, arr2), axis =-1)
print(result)

[[[ 1 11]
  [ 2 12]
  [ 3 13]
  [ 4 14]]

 [[ 6 15]
  [ 7 16]
  [ 8 17]
  [ 9 18]]]


In [ ]:
arr1 = np.array([[1,2,3,4],
                [6,7,8,9]])
arr2 = np.array([[11,12,13,14],
                 [15,16,17,18]])

result = np.stack((arr1, arr2), axis = 2)
print(result)

[[[ 1 11]
  [ 2 12]
  [ 3 13]
  [ 4 14]]

 [[ 6 15]
  [ 7 16]
  [ 8 17]
  [ 9 18]]]


**Numpy** **Arrays** **Spliting**

In [ ]:
# Split the array in 3 parts:

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
'''
We also have the method split() available but it will not adjust the elements
when elements are less in source array for splitting like in example above,
array_split() worked properly but split() would fail.
'''
# Split the array in 4 parts:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
# Access the splitted arrays:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [ ]:
# Split the 2-D array into three 2-D arrays.
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
# Split the 2-D array into three 2-D arrays.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
# Split the 2-D array into three 2-D arrays along columns.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
# Use the hsplit() method to split the 2-D array into three 2-D arrays along columns.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
arr = np.arange(13)
print(arr)
arr2 = np.array_split(arr,3)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]


In [ ]:
# Creating a 2D array
array = np.array([[3, 2, 1], [8, 9, 7], [4, 6, 5]])

# Splitting the array into 3 equal parts along the second axis (axis=1)
result = np.split(array, 3, axis=1)

print(array)
print()
print(result)

[[3 2 1]
 [8 9 7]
 [4 6 5]]

[array([[3],
       [8],
       [4]]), array([[2],
       [9],
       [6]]), array([[1],
       [7],
       [5]])]


In [ ]:
# array
arr = np.arange(9).reshape(3, 3)

# Split into 3 equal sub-arrays
split_arr = np.split(arr, 3, axis=1)

print("Original Array:")
print(arr)
print("\nSplit into 3 equal sub-arrays along axis 1:")
for sub_arr in split_arr:
   print(sub_arr)

Original Array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Split into 3 equal sub-arrays along axis 1:
[[0]
 [3]
 [6]]
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]


In [ ]:
# array
arr = np.arange(9).reshape(3, 3)

# Split array at specified indices
split_arr = np.split(arr, [1, 2], axis=0)
print("\nSplit at indices [1, 2] along axis 0:")
for sub_arr in split_arr:
   print(sub_arr)


Split at indices [1, 2] along axis 0:
[[0 1 2]]
[[3 4 5]]
[[6 7 8]]


**Numpy** **Arrays** **Searching**

In [ ]:
# Find the indexes where the value is 4:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [ ]:
# Find the indexes where the values are even:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7]),)


In [ ]:
# Find the indexes where the values are odd:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)
print(x)

(array([0, 2, 4, 6]),)


In [ ]:
array = np.array([10, 20, 30, 40, 50])
indices = np.where(array > 25)
print(indices)

modified_array = np.where(array > 25, array, 0)
print(modified_array)

(array([2, 3, 4]),)
[ 0  0 30 40 50]


In [ ]:
array = np.array([0, 1, 2, 0, 3, 0, 4])
nonzero_indices = np.nonzero(array)
print("Indices of non-zero elements:", nonzero_indices)

Indices of non-zero elements: (array([1, 2, 4, 6]),)


In [ ]:
# Find the indexes where the value 7 should be inserted
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)


1


In [ ]:
# Find the indexes where the value 7 should be inserted, starting from the right:

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='left')
print(x)

1


In [ ]:
# Find the indexes where the value 7 should be inserted, starting from the right:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
print(x)

2


In [ ]:
sorted_array = np.array([1, 3, 5, 7, 9])
values = np.array([2, 4, 6])
indices = np.searchsorted(sorted_array, values)
print("Indices where values should be inserted:", indices)

Indices where values should be inserted: [1 2 3]


In [ ]:
array = np.array([[10, 15, 5], [7, 12, 20]])
index_of_max_along_axis = np.argmax(array, axis=1)
print("Indices of the maximum values along axis 1:", index_of_max_along_axis)

Indices of the maximum values along axis 1: [1 2]


In [ ]:
array = np.array([[10, 15, 5], [7, 12, 20]])
index_of_max_flattened = np.argmax(array)
print("Index of the maximum value in the flattened array:", index_of_max_flattened)

Index of the maximum value in the flattened array: 5


In [ ]:
array = np.array([[10, 15, 5], [7, 12, 2]])
index_of_min_along_axis = np.argmin(array, axis=1)
print("Indices of the minimum values along axis 1:", index_of_min_along_axis)

Indices of the minimum values along axis 1: [2 2]


In [ ]:
array = np.array([10, 20, 30, 40, 50])
condition = array > 25
extracted_elements = np.extract(condition, array)
print("Elements greater than 25:", extracted_elements)

Elements greater than 25: [30 40 50]


In [ ]:
array = np.array([10, 20, 30, 40, 50])
boolean_mask = array > 25
filtered_array = array[boolean_mask]
print("Filtered array (elements > 25):", filtered_array)

Filtered array (elements > 25): [30 40 50]


**Numpy** **Arrays** **Sorting**

In [ ]:
# Sort the array:
arr = np.array([3, 2, 0, 1])
sorted_arr = np.sort(arr)
print(sorted_arr)

[0 1 2 3]


In [ ]:
# Sort the array alphabetically:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))


['apple' 'banana' 'cherry']


In [ ]:
# Sort a boolean array:
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [ ]:
# Sort a 2-D array:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
a = np.array([[3,4],[5,2]])
print('array:', a)
print('sorted array:', np.sort(a))
print('sorted array along row:', np.sort(a, axis = 0))
print('sorted array along columns:', np.sort(a, axis = 1))
dt = np.dtype([('name', 'S10'), ('age', int)])
a = np.array([("raju", 21), ("anil", 25), ("ravi", 17), ("amar", 27)], dtype=dt)
print("Our array is:",a)
print("Order by name:",np.sort(a, order='name'))




array: [[3 4]
 [5 2]]
sorted array: [[3 4]
 [2 5]]
sorted array along row: [[3 2]
 [5 4]]
sorted array along columns: [[3 4]
 [2 5]]
Our array is: [(b'raju', 21) (b'anil', 25) (b'ravi', 17) (b'amar', 27)]
Order by name: [(b'amar', 27) (b'anil', 25) (b'raju', 21) (b'ravi', 17)]


**Numpy** **Arrays** **Filtering**

In [ ]:
# Create an array from the elements on index
import numpy as np
arr1 = np.array([5,1,21,25,31,32,35,107])
x = [True, False, True, False, True, False, True, False]
newarr = arr1[x]
print(newarr)

# Because the new array contains only the values where the filter array had the value True,

[ 5 21 31 35]


In [ ]:
# Create a filter array that will return only values higher than 31
import numpy as np
array = np.array([5, 1, 21, 25, 31, 32, 35, 107])
filter_array = []
for element in array:
  if element > 31:
    filter_array.append(True)
  else:
    filter_array.append(False)
newarr = array[filter_array]
print(filter_array)
print(newarr)



[False, False, False, False, False, True, True, True]
[ 32  35 107]


In [ ]:
# Create a filter array that will return only even elements from the original array:

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [ ]:
# Create a filter array that will return only values higher than 42

import numpy as np
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [ ]:
# Create a filter array that will return only even elements from the original array:

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


**Numpy** **Arrays** **Boardcasting**

In [ ]:
import numpy as np
array2d = np.array([[1,5,4,2],[6,3,4,7]])
scalar = 10
newarray = array2d + scalar
print(newarray)



[[11 15 14 12]
 [16 13 14 17]]


In [ ]:
#  It adds a scalar value 1 to each element of the array using broadcasting.

import numpy as np
arr = np.array([1, 2, 3])
res = arr + 1
print(res)

[2 3 4]


In [ ]:
# NumPy automatically expands the 1D array along the rows of the 2D array to perform element-wise addition.

import numpy as np
a1 = np.array([2, 4, 6])
a2 = np.array([[1, 3, 5], [7, 9, 11]])
res = a1 + a2
print(res)

In [ ]:
# check which elements in the ages array are greater than 18. Instead of looping

import numpy as np
age = np.array([12,31,42,32,18,10,20,5,3])
persons = np.array(['adult', 'minor'])
results = np.where(age > 18, persons[0], persons[1])
print(results)

['minor' 'adult' 'adult' 'adult' 'minor' 'minor' 'adult' 'minor' 'minor']


In [ ]:
# Using Broadcasting for Matrix Multiplication
import numpy as np
matrix = np.array([[1, 2], [3, 4]])
vector = np.array([10, 20])
result = matrix * vector
print(result)

[[10 40]
 [30 80]]


**Example : 05**: **Scaling Data with Broadcasting**

*Consider* a real-world scenario where we need to calculate the total calories in foods based on the amount of fats, proteins and carbohydrates. Each nutrient has a specific caloric value per gram.


---


*Fats*: 9 calories per gram (CPG)

*Proteins*: 4 CPG

*Carbohydrates*: 4 CPG


In [ ]:
import numpy as np
food_data = np.array([[0.8, 2.9, 3.9],
                      [52.4, 23.6, 36.5],
                      [55.2, 31.7, 23.9],
                      [14.4, 11, 4.9]])

caloric_values = np.array([3, 3, 8])

caloric_matrix = caloric_values

calorie_breakdown = food_data * caloric_matrix
print(calorie_breakdown)

[[  2.4   8.7  31.2]
 [157.2  70.8 292. ]
 [165.6  95.1 191.2]
 [ 43.2  33.   39.2]]


In [ ]:
# Adjusting Temperature Data Across Multiple Locations.

import numpy as np

temperatures = np.array([
    [30, 32, 34, 33, 31],
    [25, 27, 29, 28, 26],
    [20, 22, 24, 23, 21]
])

corrections = np.array([1.5, -0.5, 2.0])

adjusted_temperatures = temperatures + corrections[:, np.newaxis]
print(adjusted_temperatures)

[[31.5 33.5 35.5 34.5 32.5]
 [24.5 26.5 28.5 27.5 25.5]
 [22.  24.  26.  25.  23. ]]


In [ ]:
# Normalizing Image Data

import numpy as np

image = np.array([
    [100, 120, 130],
    [90, 110, 140],
    [80, 100, 120]
])

mean = image.mean(axis=0)
std = image.std(axis=0)

normalized_image = (image - mean) / std
print(normalized_image)

[[ 1.22474487  1.22474487  0.        ]
 [ 0.          0.          1.22474487]
 [-1.22474487 -1.22474487 -1.22474487]]


In [ ]:
# Centering Data in Machine Learning

import numpy as np

data = np.array([
    [10, 20],
    [15, 25],
    [20, 30]
])

feature_mean = data.mean(axis=0)

centered_data = data - feature_mean
print(centered_data)

[[-5. -5.]
 [ 0.  0.]
 [ 5.  5.]]
