# **Mathematical Operations in NumPY**

**Numpy** **Arithmetic** **Operations**

In [ ]:
# Addition
import numpy as np
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
add_ans = np.add(a,b)
print(add_ans)

[2 4 6 8]


In [ ]:
# Subtraction
import numpy as np

a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
sub_ans = np.subtract(a, b)
print(sub_ans)

[ 3 67  3 70]


In [ ]:
# Multiplication
import numpy as np

a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
mul_ans = np.multiply(a, b)
print(mul_ans)

[  10  360  130 3000]


In [ ]:
# Division
import numpy as np

a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
div_ans = np.divide(a, b)
print(div_ans)

[ 2.5        14.4         1.3         3.33333333]


In [ ]:
# Exponentiation

import numpy as np

a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
pow_ans = np.power(a, b)
print(pow_ans)

[                 25          1934917632        137858491849
 1152921504606846976]


In [ ]:
# Modulus

import numpy as np
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
mod_ans = np.mod(a, b)
print(mod_ans)

[ 1  2  3 10]


**Aggregate** **Functions**

numpy.sum methods

In [ ]:
# (1)
'''
This Python program uses numpy.sum() to calculate the sum of a 1D array.
It demonstrates summing with different data types (uint8 and float32) and
checks if the result's data type matches np.uint and np.float.
The output shows how the sum can vary with different types.
'''

import numpy as np

arr = [20, 2, .2, 10, 4]

print("\nSum of arr : ", np.sum(arr))
print("Sum of arr(uint8) : ", np.sum(arr, dtype = np.uint8))
print("Sum of arr(float32) : ", np.sum(arr, dtype = np.float32))

print ("Is np.sum(arr).dtype == np.uint : ", np.sum(arr).dtype == np.uint)   # np.uint -> use np.uint64

print ("Is np.sum(arr).dtype == float : ", np.sum(arr).dtype == float)       # np.float -> use float



Sum of arr :  36.2
Sum of arr(uint8) :  36
Sum of arr(float32) :  36.2
Is np.sum(arr).dtype == np.uint :  False
Is np.sum(arr).dtype == float :  True


In [ ]:
# (2)
'''This Python program uses NumPy to compute the sum of a 2D array arr with different data types.
It demonstrates the use of np.sum() to calculate the sum of elements in arr and
outputs results for different data types (uint8 and float32).
It also checks if the sum's data type matches np.uint or np.float.
'''
import numpy as np

# 2D array
arr = [[14, 17, 12, 33, 44],
	[15, 6, 27, 8, 19],
	[23, 2, 54, 1, 4,]]

print("\nSum of arr : ", np.sum(arr))

print("Sum of arr(uint8) : ", np.sum(arr, dtype = np.uint8))
print("Sum of arr(float32) : ", np.sum(arr, dtype = np.float32))

print ("\nIs np.sum(arr).dtype == np.uint : ",
				np.sum(arr).dtype == np.uint)

print ("Is np.sum(arr).dtype == float : ",
			np.sum(arr).dtype == float)


Sum of arr :  279
Sum of arr(uint8) :  23
Sum of arr(float32) :  279.0

Is np.sum(arr).dtype == np.uint :  False
Is np.sum(arr).dtype == float :  False


In [ ]:
# (3)
'''This Python program uses numpy.sum() to compute the sum of elements in a 2D array.
It calculates the total sum, sums along rows (axis=0),
sums along columns (axis=1), and sums along columns while keeping the dimensions (keepdims=True).
'''

import numpy as np

# 2D array
arr = [[14, 17, 12, 33, 44],
	[15, 6, 27, 8, 19],
	[23, 2, 54, 1, 4,]]

print("\nSum of arr : ", np.sum(arr))
print("Sum of arr(axis = 0) : ", np.sum(arr, axis = 0))
print("Sum of arr(axis = 1) : ", np.sum(arr, axis = 1))

print("\nSum of arr (keepdimension is True): \n",
	np.sum(arr, axis = 1, keepdims = True))


Sum of arr :  279
Sum of arr(axis = 0) :  [52 25 93 42 67]
Sum of arr(axis = 1) :  [120  75  84]

Sum of arr (keepdimension is True): 
 [[120]
 [ 75]
 [ 84]]


numpy.mean methods

In [ ]:
# 1

import numpy as np
# 1D array
arr = [20, 2, 7, 1, 34]

print("arr : ", arr)
print("mean of arr : ", np.mean(arr))

arr :  [20, 2, 7, 1, 34]
mean of arr :  12.8


In [ ]:
# 2

import numpy as np
# 2D array
arr = [[14, 17, 12, 33, 44],
       [15, 6, 27, 8, 19],
       [23, 2, 54, 1, 4, ]]

# mean of the flattened array
print("\nmean of arr, axis = None : ", np.mean(arr))

# mean along the axis = 0
print("\nmean of arr, axis = 0 : ", np.mean(arr, axis = 0))

# mean along the axis = 1
print("\nmean of arr, axis = 1 : ", np.mean(arr, axis = 1))

out_arr = np.arange(3)
print("\nout_arr : ", out_arr)
print("mean of arr, axis = 1 : ",
      np.mean(arr, axis = 1, out = out_arr))


mean of arr, axis = None :  18.6

mean of arr, axis = 0 :  [17.33333333  8.33333333 31.         14.         22.33333333]

mean of arr, axis = 1 :  [24.  15.  16.8]

out_arr :  [0 1 2]
mean of arr, axis = 1 :  [24 15 16]


numpy.maximum method

In [ ]:
# 1

import numpy as np
in_num1 = 10
in_num2 = 21

print ("Input  number1 : ", in_num1)
print ("Input  number2 : ", in_num2)

out_num = np.maximum(in_num1, in_num2)
print ("maximum of 10 and 21 : ", out_num)

Input  number1 :  10
Input  number2 :  21
maximum of 10 and 21 :  21


In [ ]:
# 2

import numpy as np
in_arr1 = [2, 8, 125]
in_arr2 = [3, 3, 15]

print ("Input array1 : ", in_arr1)
print ("Input array2 : ", in_arr2)

out_arr = np.maximum(in_arr1, in_arr2)
print ("Output array after selecting maximum: ", out_arr)

Input array1 :  [2, 8, 125]
Input array2 :  [3, 3, 15]
Output array after selecting maximum:  [  3   8 125]


In [ ]:
# 3

import numpy as np

in_arr1 = [np.nan, 0, np.nan]
in_arr2 = [np.nan, np.nan, 0]

print ("Input array1 : ", in_arr1)
print ("Input array2 : ", in_arr2)

out_arr = np.maximum(in_arr1, in_arr2)
print ("Output array after selecting maximum: ", out_arr)

Input array1 :  [nan, 0, nan]
Input array2 :  [nan, nan, 0]
Output array after selecting maximum:  [nan nan nan]


numpy.minimum methods

In [ ]:
# Python program explaining
# minimum() function

import numpy as geek
in_num1 = 10
in_num2 = 21

print ("Input  number1 : ", in_num1)
print ("Input  number2 : ", in_num2)

out_num = geek.minimum(in_num1, in_num2)
print ("minimum of 10 and 21 : ", out_num)

In [ ]:
# Python program explaining
# minimum() function

import numpy as geek

in_arr1 = [2, 8, 125]
in_arr2 = [3, 3, 15]

print ("Input array1 : ", in_arr1)
print ("Input array2 : ", in_arr2)

out_arr = geek.minimum(in_arr1, in_arr2)
print ("Output array after selecting minimum: ", out_arr)

In [ ]:
# Python program explaining
# minimum() function

import numpy as geek

in_arr1 = [geek.nan, 0, geek.nan]
in_arr2 = [geek.nan, geek.nan, 0]

print ("Input array1 : ", in_arr1)
print ("Input array2 : ", in_arr2)

out_arr = geek.minimum(in_arr1, in_arr2)
print ("Output array after selecting minimum: ", out_arr)

Input array1 :  [nan, 0, nan]
Input array2 :  [nan, nan, 0]
Output array after selecting minimum:  [nan nan nan]


**Numpy** **Universal** **Functions**

In [ ]:
# Python code to demonstrate trigonometric function
import numpy as np

# create an array of angles
angles = np.array([0, 30, 45, 60, 90, 180])

# conversion of degree into radians
# using deg2rad function
radians = np.deg2rad(angles)

# sine of angles
print('Sine of angles in the array:')
sine_value = np.sin(radians)
print(np.sin(radians))

# inverse sine of sine values
print('Inverse Sine of sine values:')
print(np.rad2deg(np.arcsin(sine_value)))

# hyperbolic sine of angles
print('Sine hyperbolic of angles in the array:')
sineh_value = np.sinh(radians)
print(np.sinh(radians))

# inverse sine hyperbolic
print('Inverse Sine hyperbolic:')
print(np.sin(sineh_value))

# hypot function demonstration
base = 4
height = 3
print('hypotenuse of right triangle is:')
print(np.hypot(base, height))

Sine of angles in the array:
[0.00000000e+00 5.00000000e-01 7.07106781e-01 8.66025404e-01
 1.00000000e+00 1.22464680e-16]
Inverse Sine of sine values:
[0.0000000e+00 3.0000000e+01 4.5000000e+01 6.0000000e+01 9.0000000e+01
 7.0167093e-15]
Sine hyperbolic of angles in the array:
[ 0.          0.54785347  0.86867096  1.24936705  2.3012989  11.54873936]
Inverse Sine hyperbolic:
[ 0.          0.52085606  0.76347126  0.94878485  0.74483916 -0.85086591]
hypotenuse of right triangle is:
5.0


In [ ]:
# Python code demonstrate statistical function
import numpy as np

# construct a weight array
weight = np.array([50.7, 52.5, 50, 58, 55.63, 73.25, 49.5, 45])

# minimum and maximum
print('Minimum and maximum weight of the students: ')
print(np.amin(weight), np.amax(weight))

# range of weight i.e. max weight-min weight
print('Range of the weight of the students: ')
print(np.ptp(weight))

# percentile
print('Weight below which 70 % student fall: ')
print(np.percentile(weight, 70))

# mean
print('Mean weight of the students: ')
print(np.mean(weight))

# median
print('Median weight of the students: ')
print(np.median(weight))

# standard deviation
print('Standard deviation of weight of the students: ')
print(np.std(weight))

# variance
print('Variance of weight of the students: ')
print(np.var(weight))

# average
print('Average weight of the students: ')
print(np.average(weight))

Minimum and maximum weight of the students: 
45.0 73.25
Range of the weight of the students: 
28.25
Weight below which 70 % student fall: 
55.317
Mean weight of the students: 
54.3225
Median weight of the students: 
51.6
Standard deviation of weight of the students: 
8.052773978574091
Variance of weight of the students: 
64.84716875
Average weight of the students: 
54.3225


In [ ]:
# Python code to demonstrate bitwise-function
import numpy as np

# construct an array of even and odd numbers
even = np.array([0, 2, 4, 6, 8, 16, 32])
odd = np.array([1, 3, 5, 7, 9, 17, 33])

# bitwise_and
print('bitwise_and of two arrays: ')
print(np.bitwise_and(even, odd))

# bitwise_or
print('bitwise_or of two arrays: ')
print(np.bitwise_or(even, odd))

# bitwise_xor
print('bitwise_xor of two arrays: ')
print(np.bitwise_xor(even, odd))

# invert or not
print('inversion of even no. array: ')
print(np.invert(even))

# left_shift
print('left_shift of even no. array: ')
print(np.left_shift(even, 1))

# right_shift
print('right_shift of even no. array: ')
print(np.right_shift(even, 1))

bitwise_and of two arrays: 
[ 0  2  4  6  8 16 32]
bitwise_or of two arrays: 
[ 1  3  5  7  9 17 33]
bitwise_xor of two arrays: 
[1 1 1 1 1 1 1]
inversion of even no. array: 
[ -1  -3  -5  -7  -9 -17 -33]
left_shift of even no. array: 
[ 0  4  8 12 16 32 64]
right_shift of even no. array: 
[ 0  1  2  3  4  8 16]
