# **Linear Algebra With NumPy**

**Numpy** **Multiplication and Manipulation** **Functions**

In [ ]:
# Python code to demonstrate matrix operations
# add(), subtract() and divide()

# importing numpy for matrix operations
import numpy

# initializing matrices
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])

# using add() to add matrices
print ("The element wise addition of matrix is : ")
print (numpy.add(x,y))

# using subtract() to subtract matrices
print ("The element wise subtraction of matrix is : ")
print (numpy.subtract(x,y))

# using divide() to divide matrices
print ("The element wise division of matrix is : ")
print (numpy.divide(x,y))

The element wise addition of matrix is : 
[[ 8 10]
 [13 15]]
The element wise subtraction of matrix is : 
[[-6 -6]
 [-5 -5]]
The element wise division of matrix is : 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


In [ ]:
# Python code to demonstrate matrix operations
# multiply() and dot()

# importing numpy for matrix operations
import numpy

# initializing matrices
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])

# using multiply() to multiply matrices element wise
print ("The element wise multiplication of matrix is : ")
print (numpy.multiply(x,y))

# using dot() to multiply matrices
print ("The product of matrices is : ")
print (numpy.dot(x,y))

The element wise multiplication of matrix is : 
[[ 7 16]
 [36 50]]
The product of matrices is : 
[[25 28]
 [73 82]]


In [ ]:
# Python code to demonstrate matrix operations
# sqrt(), sum() and "T"

# importing numpy for matrix operations
import numpy

# initializing matrices
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])

# using sqrt() to print the square root of matrix
print ("The element wise square root is : ")
print (numpy.sqrt(x))
print (numpy.sqrt(y))

# using sum() to print summation of all elements of matrix
print ("The summation of all matrix element is : ")
print (numpy.sum(x))
print (numpy.sum(y))

# using sum(axis=0) print summation of each column of matrix
print ("The column wise summation of all matrix is : ")
print (numpy.sum(x,axis=0))
print (numpy.sum(y,axis=0))

# using sum(axis=1) print summation of each row of matrix
print ("The row wise summation of all matrix is : ")
print (numpy.sum(x,axis=1))
print (numpy.sum(y,axis=1))

# using "T" to transpose the matrix
print ("The transpose of given matrix is : ")
print (x.T)
print (y.T)

The element wise square root is : 
[[1.         1.41421356]
 [2.         2.23606798]]
[[2.64575131 2.82842712]
 [3.         3.16227766]]
The summation of all matrix element is : 
12
34
The column wise summation of all matrix is : 
[5 7]
[16 18]
The row wise summation of all matrix is : 
[3 9]
[15 19]
The transpose of given matrix is : 
[[1 4]
 [2 5]]
[[ 7  9]
 [ 8 10]]


**Products of Vectors and Matrices in NumPy**

In [ ]:
import numpy as np

a = np.array([2, 6])
b = np.array([3, 10])
print("Vectors :")
print("a = ", a)
print("b = ", b)

print("\nInner product of vectors a and b =")
print(np.inner(a, b))

print("\n---------------------------------------")

x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print("\nMatrices :")
print("x =", x)
print("ny =", y)

print("\nInner product of matrices x and y =")
print(np.inner(x, y))

Vectors :
a =  [2 6]
b =  [ 3 10]

Inner product of vectors a and b =
66

---------------------------------------

Matrices :
x = [[2 3 4]
 [3 2 9]]
ny = [[ 1  5  0]
 [ 5 10  3]]

Inner product of matrices x and y =
[[17 52]
 [13 62]]


In [ ]:
import numpy as np

a = np.array([2, 6])
b = np.array([3, 10])
print("Vectors :")
print("a = ", a)
print("\nb = ", b)

print("\nOuter product of vectors a and b =")
print(np.outer(a, b))

print("\n------------------------------------")

x = np.array([[3, 6, 4], [9, 4, 6]])
y = np.array([[1, 15, 7], [3, 10, 8]])
print("\nMatrices :")
print("x =", x)
print("\ny =", y)

print("\nOuter product of matrices x and y =")
print(np.outer(x, y))

Vectors :
a =  [2 6]

b =  [ 3 10]

Outer product of vectors a and b =
[[ 6 20]
 [18 60]]

------------------------------------

Matrices :
x = [[3 6 4]
 [9 4 6]]

y = [[ 1 15  7]
 [ 3 10  8]]

Outer product of matrices x and y =
[[  3  45  21   9  30  24]
 [  6  90  42  18  60  48]
 [  4  60  28  12  40  32]
 [  9 135  63  27  90  72]
 [  4  60  28  12  40  32]
 [  6  90  42  18  60  48]]
